### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by rileytg** [farfromrefug/react-xterm#1]
(Thanks for putting this component together, works perfectly for my needs)

I included the CSS from upstream xterm releases (totally works for me). How do you recommend including it? 

I haven't seen much about this kinda thing (css) in 3rd party React components. 

Ideally I'd like to 
```js
import 'react-xterm/css'
```
or something along those lines...

**Comment by farfromrefug** [comment]
@rileytg you should not include the css in that react module. It comes with the xterm module.
```react-xterm``` requires ```xterm``` thus the css is in ```node_modules/xterm```

**Comment by rileytg** [comment]
👌
