### ISSUE TITLE
Buffer the input data to server with a debounce

### ISSUE THREAD

**Issue by veeramarni** [farfromrefug/react-xterm#10]
Question on how to make the frontend server less chatty. Instead of sending every key entered to the backend, how can we buffer the data and send to the backend after every <specified> second. Also, we capture certain keystrokes such as`enter key`etc. to invoke an action to send the data to the backend server. We also need to make sure the inputted data printed on the UI won't be printed again in the UI if it sends back from the server.

Let me know if you have any thoughts?

**Comment by farfromrefug** [comment]
@veeramarni you are asking in the wrong repo. this is just a graphic comoonent
