### ISSUE TITLE
How in JS

### ISSUE THREAD

**Issue by Planeurzik** [farfromrefug/react-xterm#11]
I've got an issue about making Xterm work with Javascript, i tried the code in the /dist/examples/javascript but it doesn't work... Do I need to use typescript ?

**Comment by farfromrefug** [comment]
@Planeurzik what s your error?

**Comment by jloveric** [comment]
Yes, I also get an error.  You should put in a simple example in the README about how to use this as I think it would be popular.
```
./node_modules/react-xterm/node_modules/xterm/dist/addons/attach/attach.test.js
Module not found: Can't resolve 'chai' in '.../node_modules/react-xterm/node_modules/xterm/dist/addons/attach'
```

**Comment by farfromrefug** [comment]
@jloveric are you willing to make a PR?
I actually dont work/use this right now. Long time since i have used react :s

**Comment by Guneetgstar** [comment]
@farfromrefug I can help in maintaining the repo if you help me setting up this project.

**Comment by farfromrefug** [comment]
@Guneetgstar sure what do you need to know?

**Comment by Guneetgstar** [comment]
Currently, I am getting the same error @jloveric has mentioned.
I have installed this dependency using `npm install react-xterm`

**Comment by farfromrefug** [comment]
@Guneetgstar this is an `xterm` error!
It might related to your `xterm` version i really don't know
The easy would be to install chai.

**Comment by Guneetgstar** [comment]
@farfromrefug Install chai? What is chai?

**Comment by Guneetgstar** [comment]
As far as I understand `chai` is something required by the `xterm` and `react-exterm` is using the that source.
I have installed `xterm` and its working just fine but to make it a react component I either start writing the whole code from scratch or I can just use the code here.

> @Guneetgstar this is an `xterm` error!
> It might related to your `xterm` version i really don't know
> The easy would be to install chai.

**Comment by farfromrefug** [comment]
@Guneetgstar i dont understand your point.
You can use this component then? You just need to add chai as a dependency?
If so then it is a matter of updating the package.json

**Comment by Guneetgstar** [comment]
@farfromrefug Thanks! It just worked. Actually the `chai` was not the only one but one of the many dependencies that `xterm` requires and unfortunately, `xterm` was not in my `package.json`. Ideally, there should be an assert `require('xterm')` in `react-xterm`. 
I will create a pull request soon for this, meanwhile, you can close this issue.

**Comment by Guneetgstar** [comment]
Coming back to you @Planeurzik there is nothing special about JS. Just read the [README.md](https://github.com/farfromrefug/react-xterm/blob/master/README.md) and you will be good to keep going.

**Comment by ruchit-cognicept** [comment]
Seems the PR for this fix is approved, but not pushed for the npm package.

**Comment by Guneetgstar** [comment]
@ruchit-cognicept  You can create a new issue for that.
