### ISSUE TITLE
Update xterm?

### ISSUE THREAD

**Issue by lukevp** [farfromrefug/react-xterm#16]
This project is a few years behind current xterm. Are you able to update to the latest xterm and push a new npm package? If not, would you be willing to pass along maintenance of this and the npm package so I could keep this updated? I would gladly take over if you’d like.

**Comment by farfromrefug** [comment]
@lukevp best would be for to start maintaining it.
I will add you here. Need to allow you to release on npm so i need to username their.

**Comment by lukevp** [comment]
@farfromrefug sounds good. My name on npm is the same. https://www.npmjs.com/~lukevp

**Comment by lukevp** [comment]
@farfromrefug are you ok if I add a license under MIT for this package? It doesn’t appear to have a  current license and MIT is most common/permissive for end users.

**Comment by farfromrefug** [comment]
@lukevp you should be able to release on npm now.
Do what you think is best. The most permissive license the better!
