### ISSUE TITLE
addons should be props ?

### ISSUE THREAD

**Issue by ltaoo** [farfromrefug/react-xterm#9]
https://github.com/farfromrefug/react-xterm/blob/3cd1a1916a0d1b6c983da46e3b7926ac5a5216d9/example/javascripts/index.tsx#L36

**Comment by farfromrefug** [comment]
What do you mean?
You don't need to do it that way. I like to do it that way ;)

**Comment by learningdesignlabs** [comment]
I think Itaoo meant, addons should be props instead of an array in styles.. since add-ons extend beyond the scope of styles?
